import React from 'react';
import styles from './styles.module.css'

export const metadata = {
    title: 'about',
    description: 'Generated by create next app',
}


export default function AboutLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <nav>about nav</nav>
            <main className={styles.main}>
                {children}

            </main>
        </>
    )
}
